# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/TAN/Desktop/SM/SM.cache/wt [current_project]
set_property parent.project_path C:/Users/TAN/Desktop/SM/SM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/FloatAdder.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/FpMultiplier.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/RegFile.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/ControlUnit.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/ALU.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/SharedMemory.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/MultithreadedInstructionUnit.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/MulticastNetwork.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/Instruction_Cache.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/StreamProcessor.v
  C:/Users/TAN/Desktop/SM/SM.srcs/sources_1/new/StreamingMultiprocesser.v
}
synth_design -top StreamingMultiprocesser -part xc7a35tcpg236-1
write_checkpoint -noxdef StreamingMultiprocesser.dcp
catch { report_utilization -file StreamingMultiprocesser_utilization_synth.rpt -pb StreamingMultiprocesser_utilization_synth.pb }
